### ISSUE TITLE
Missing test files

### ISSUE THREAD

**Issue by jaredsmith** [micromatch/posix-character-classes#1]
This package seems to be missing its test files, as "npm test" runs mocha, but mocha doesn't find a test.js file or test/ directory.

Was this an oversight, or are there no tests for this package?

**Comment by jonschlinkert** [comment]
@jaredsmith thanks, although this lib just exports and array of strings, I think we should always have tests, even as a sanity check. I'll push up a test.js file. Thanks for pointing this out.
