### ISSUE TITLE
graph vs space vs cntrl

### ISSUE THREAD

**Issue by AloisMahdal** [micromatch/posix-character-classes#3]
Following does not add up with regards to `0x20` space:
 *  Equivalence note on `[:graph:]` says `[^[:cntrl:]]`.
 *  Description on `[:graph:]` says "graphic characters (all characters which have graphic representation)".
 *   `[:graph:]` is defined as `0x21-0xFE`, and `[:cntrl:]` as `0x00-0x1F`.

`0x20` does not have graphic representation, and is not a control character, so `graph` being `0x21-0xFE` is correct, but the equivalence note and description are inaccurate.

I haven't consulted POSIX, but I have checked grep, and `graph` does not catch space:

    $ grep -o '[[:graph:]]*' <<<"a b c"
    a
    b
    c
    $

**Comment by doowb** [comment]
From looking at [the referenced wiki table](https://en.wikibooks.org/wiki/Regular_Expressions/POSIX_Basic_Regular_Expressions#Character_classes), it looks like there's a space in `[^ [:cntrl:]]`. I think it's just a typo in this README.

**Comment by jonschlinkert** [comment]
> I think it's just a typo in this README.

It might be. Sometimes GitHub's markdown parser mangles special characters, and sometimes our tooling does. Just mentioning that in case you "fix" something and then notice it repear.

**Comment by AloisMahdal** [comment]
Well it looks like a typo but also the original wiki document does not
match with [POSIX][]:

> * **graph**
>
> Define characters to be classified as printable characters, not
> including the `<space>`.
>
> In the POSIX locale, all characters in classes alpha, digit, and punct
> shall be included; no characters in class cntrl shall be included.
>
> In a locale definition file, characters specified for the keywords
> upper, lower, alpha, digit, xdigit, and punct are automatically included
> in this class. No character specified for the keyword cntrl shall be
> specified.

  [POSIX]: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap07.html#tag_07_03_01

...which is also what I've observed with grep.

**Comment by AloisMahdal** [comment]
I've posted edit to the wiki page, so you should see it fixed there..

**Comment by AloisMahdal** [comment]
Umm, wait, i acted too fast.  `[^ [:cntrl:]]` on the original wiki page is correct (I've reverted my edit now).
